name: Release

on:
#   schedule:
#     - cron: '0 0 */10 * *'
  workflow_dispatch:

jobs:
  build:
    name: Build Output
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.7'

      - name: Setup Go 1.x.y
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17.1

      - name: Env
        run: |
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "RELEASE_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          
      - name: Download all resources
        run: |
          mkdir -p resources
          rm -rf resources/*
          cd scripts || exit

          sh ito_gov_downloader.sh
          sh geolite2_downloader.sh ${{ secrets.GEOLITE2_TOKEN }}
          sh ip2location_downloader.sh ${{ secrets.IP2LOCATION_TOKEN }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt update
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Run python program
        run: |
          python src/main.py

      - name: Build .dat file
        run: |
          git clone https://github.com/v2fly/geoip.git
          rm -rf geoip/config*
          
          cp output/iran_ips.txt geoip/ir.txt
          cp v2ray_config.json geoip/config.json
          
          cd geoip
          go run ./
          cd ..

          cp geoip/output/dat/irip.dat output/
      
      - name: Upload result as release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "output/*.*"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.TAG_NAME }}
          name: ${{ env.RELEASE_NAME }}
